package com.fatec.scel;

/// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class REQ03CT01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rEQ03CT01() {
    driver.get("https://ts-scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(865, 693));
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("2001");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Fulano");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fulano@gmail.com");
    driver.findElement(By.id("cep")).click();
    driver.findElement(By.id("cep")).sendKeys("03654000");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector(".panel-body")).click();
    driver.findElement(By.cssSelector(".panel-body")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("2001"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3)")).getText(), is("Fulano"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4)")).getText(), is("fulano@gmail.com"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(5)")).getText(), is("03654000"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(6)")).getText(), is("Rua Almeria"));
  }
}
