package com.fatec.scel;

// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
public class REQ02CT11Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @org.junit.jupiter.api.Test
  public void rEQ02CT11() {
    driver.get("https://ts-scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(598, 768));
    driver.findElement(By.name("username")).click();
	driver.findElement(By.name("username")).sendKeys("jose");
	driver.findElement(By.name("password")).sendKeys("123");
	driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Livros")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("8963");
    driver.findElement(By.id("autor")).sendKeys("autoriririri");
    driver.findElement(By.id("titulo")).sendKeys("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    driver.findElement(By.id("autor")).click();
    driver.findElement(By.id("autor")).click();
    {
      WebElement element = driver.findElement(By.id("autor"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("autor")).sendKeys("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.id("autor")).click();
    driver.findElement(By.id("autor")).click();
    {
      WebElement element = driver.findElement(By.id("autor"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("autor")).sendKeys("aaaaaaaaaaaaaaaaaaaaa");
    driver.findElement(By.cssSelector(".card-body")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
