package com.fatec.scel;

// Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class REQ02CT07Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @org.junit.jupiter.api.Test
  public void rEQ02CT07() {
    driver.get("https://ts-scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(598, 768));
    driver.findElement(By.name("username")).click();
	driver.findElement(By.name("username")).sendKeys("jose");
	driver.findElement(By.name("password")).sendKeys("123");
	driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Livros")).click();
    driver.findElement(By.linkText("Voltar")).click();
    driver.findElement(By.linkText("Livros")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("1232");
    driver.findElement(By.id("autor")).sendKeys("autorvalido");
    driver.findElement(By.id("titulo")).sendKeys("titulovalido");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
